"""empty message

Revision ID: e95bec3473f0
Revises: 
Create Date: 2019-05-15 16:37:05.056264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e95bec3473f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bangumi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('company', sa.String(length=160), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bangumi_name'), 'bangumi', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bangumi_name'), table_name='bangumi')
    op.drop_table('bangumi')
    # ### end Alembic commands ###
